import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const connectionString = "postgresql://postgres.wcpbuhaeqjiaylubtcpn:Pampam201201%40@aws-1-ap-south-1.pooler.supabase.com:5432/postgres";
const adapter = new PrismaPg({ connectionString });
const prisma = new PrismaClient({ adapter });

const items = [
  { no: 1, nama: "Sawi Hijau", satuan: "Kg", jenis: "BASAH" },
  { no: 2, nama: "Cabe Merah", satuan: "Kg", jenis: "BASAH" },
  { no: 3, nama: "Tomat", satuan: "Kg", jenis: "BASAH" },
  { no: 4, nama: "Bawang Putih Kupas", satuan: "Kg", jenis: "BASAH" },
  { no: 5, nama: "Bubur Kacang Ijo", satuan: "Porsi", jenis: "KERING" },
  { no: 6, nama: "Tempe", satuan: "Pcs", jenis: "BASAH" },
  { no: 7, nama: "Selada", satuan: "Ikat", jenis: "BASAH" },
  { no: 8, nama: "Puding Agar Agar", satuan: "Pcs", jenis: "KERING" },
  { no: 9, nama: "Labu Siam", satuan: "Kg", jenis: "BASAH" },
  { no: 10, nama: "Daun Jeruk", satuan: "Ikat", jenis: "BASAH" },
  { no: 11, nama: "Cabe Rawit", satuan: "Kg", jenis: "BASAH" },
  { no: 12, nama: "Bawang Merah Kupas", satuan: "Kg", jenis: "BASAH" },
  { no: 13, nama: "Ayam", satuan: "Kg", jenis: "BASAH" },
  { no: 14, nama: "Daun Bawang", satuan: "Ikat", jenis: "BASAH" },
  { no: 15, nama: "Daun Kari", satuan: "Ikat", jenis: "BASAH" },
  { no: 16, nama: "Ikan Suir", satuan: "Kg", jenis: "BASAH" },
  { no: 17, nama: "Toge", satuan: "Kg", jenis: "BASAH" },
  { no: 18, nama: "Timun", satuan: "Kg", jenis: "BASAH" },
  { no: 19, nama: "Roti Aoka", satuan: "Pcs", jenis: "KERING" },
  { no: 20, nama: "Kacang Goreng", satuan: "Kg", jenis: "KERING" },
  { no: 21, nama: "Cabe Ijo", satuan: "Kg", jenis: "BASAH" },
  { no: 22, nama: "Tahu", satuan: "Pcs", jenis: "BASAH" },
  { no: 23, nama: "Bolu Pisang", satuan: "Pcs", jenis: "KERING" },
  { no: 24, nama: "Wortel", satuan: "Kg", jenis: "BASAH" },
  { no: 25, nama: "Beef Slice", satuan: "Kg", jenis: "BASAH" },
  { no: 26, nama: "Daun Pandan", satuan: "Ikat", jenis: "BASAH" },
  { no: 27, nama: "Serai", satuan: "Ikat", jenis: "BASAH" },
  { no: 28, nama: "Ayam Giling", satuan: "Kg", jenis: "BASAH" },
  { no: 29, nama: "Bolu Labu Kuning", satuan: "Pcs", jenis: "KERING" },
  { no: 30, nama: "Buncis", satuan: "Kg", jenis: "BASAH" },
  { no: 31, nama: "Santan Kelapa", satuan: "Pack", jenis: "KERING" },
  { no: 32, nama: "Ikan Tuna", satuan: "Kg", jenis: "BASAH" },
  { no: 33, nama: "Kacang Panjang", satuan: "Ikat", jenis: "BASAH" },
  { no: 34, nama: "Daun Salam", satuan: "Ikat", jenis: "BASAH" },
  { no: 35, nama: "Puding Kacang Ijo", satuan: "Pcs", jenis: "KERING" },
  { no: 36, nama: "Bakpia", satuan: "Pcs", jenis: "KERING" },
  { no: 37, nama: "Gambas/Oyong", satuan: "Kg", jenis: "BASAH" },
  { no: 38, nama: "Dada Ayam Fillet", satuan: "Kg", jenis: "BASAH" },
  { no: 39, nama: "Daun Kemangi", satuan: "Ikat", jenis: "BASAH" },
  { no: 40, nama: "Puding Coklat", satuan: "Pcs", jenis: "KERING" },
  { no: 41, nama: "Ikan Dencis", satuan: "Kg", jenis: "BASAH" },
  { no: 42, nama: "Daun Sop", satuan: "Ikat", jenis: "BASAH" },
  { no: 43, nama: "Ikan Dori", satuan: "Kg", jenis: "BASAH" },
  { no: 44, nama: "Jeruk Nipis", satuan: "Kg", jenis: "BASAH" },
  { no: 45, nama: "Anggur Merah", satuan: "Kg", jenis: "BASAH" },
  { no: 46, nama: "Kentang Frozen", satuan: "Kg", jenis: "KERING" },
  { no: 47, nama: "Jagung", satuan: "Kg", jenis: "BASAH" },
  { no: 48, nama: "Buah Kelengkeng", satuan: "Kg", jenis: "BASAH" },
  { no: 49, nama: "Terong Ungu", satuan: "Kg", jenis: "BASAH" },
  { no: 50, nama: "Jagung Pipil Frozen", satuan: "Kg", jenis: "KERING" },
  { no: 51, nama: "Buah Pear", satuan: "Kg", jenis: "BASAH" },
  { no: 52, nama: "Kol", satuan: "Kg", jenis: "BASAH" },
  { no: 53, nama: "Roti Bun Burger", satuan: "Pcs", jenis: "KERING" },
  { no: 54, nama: "Roti Ikan", satuan: "Pcs", jenis: "KERING" },
  { no: 55, nama: "Daging Sapi Slice", satuan: "Kg", jenis: "BASAH" },
  { no: 56, nama: "Paprika Merah", satuan: "Kg", jenis: "BASAH" },
  { no: 57, nama: "Paprika Hijau", satuan: "Kg", jenis: "BASAH" },
  { no: 58, nama: "Udang", satuan: "Kg", jenis: "BASAH" },
  { no: 59, nama: "Mix Vegetables", satuan: "Kg", jenis: "KERING" },
  { no: 60, nama: "Ubi Ungu", satuan: "Kg", jenis: "BASAH" },
  { no: 61, nama: "Kue Wijen", satuan: "Pcs", jenis: "KERING" },
  { no: 62, nama: "Roti", satuan: "Pcs", jenis: "KERING" },
  { no: 63, nama: "Kentang", satuan: "Kg", jenis: "BASAH" },
  { no: 64, nama: "Sawi Putih", satuan: "Kg", jenis: "BASAH" },
  { no: 65, nama: "Roti Kacang Merah", satuan: "Pcs", jenis: "KERING" },
  { no: 66, nama: "Baby Corn", satuan: "Kg", jenis: "BASAH" },
  { no: 67, nama: "Bakso Ayam", satuan: "Kg", jenis: "KERING" },
  { no: 68, nama: "Paha Ayam Fillet", satuan: "Kg", jenis: "BASAH" },
  { no: 69, nama: "Daun Pisang", satuan: "Ikat", jenis: "BASAH" },
  { no: 70, nama: "Kurma", satuan: "Kg", jenis: "KERING" },
  { no: 71, nama: "Buah Semangka", satuan: "Kg", jenis: "BASAH" },
  { no: 72, nama: "Roti Kelapa", satuan: "Pcs", jenis: "KERING" },
  { no: 73, nama: "Roti Keju", satuan: "Pcs", jenis: "KERING" },
  { no: 74, nama: "Buah Mangga", satuan: "Kg", jenis: "BASAH" },
  { no: 75, nama: "Kue Timphan", satuan: "Pcs", jenis: "KERING" },
  { no: 76, nama: "Bolu Pandan", satuan: "Pcs", jenis: "KERING" },
  { no: 77, nama: "Risol Sayur", satuan: "Pcs", jenis: "KERING" },
  { no: 78, nama: "Buah Apel", satuan: "Kg", jenis: "BASAH" },
  { no: 79, nama: "Brownies", satuan: "Pcs", jenis: "KERING" },
  { no: 80, nama: "Lemon", satuan: "Kg", jenis: "BASAH" },
  { no: 81, nama: "Daun Kunyit", satuan: "Ikat", jenis: "BASAH" },
  { no: 82, nama: "Kelapa Gonseng", satuan: "Kg", jenis: "KERING" },
  { no: 83, nama: "Daging Sapi", satuan: "Kg", jenis: "BASAH" },
  { no: 84, nama: "Yoghurt", satuan: "Pcs", jenis: "BASAH" },
  { no: 85, nama: "Roti Hotdog", satuan: "Pcs", jenis: "KERING" },
  { no: 86, nama: "Bunga Kol", satuan: "Kg", jenis: "BASAH" },
  { no: 87, nama: "Nanas", satuan: "Kg", jenis: "BASAH" },
  { no: 88, nama: "Kulit Dimsum", satuan: "Pack", jenis: "KERING" },
  { no: 89, nama: "Paha Ayam Giling", satuan: "Kg", jenis: "BASAH" },
  { no: 90, nama: "Telur Ayam", satuan: "Papan", jenis: "KERING" },
  { no: 91, nama: "Beras", satuan: "Sak", jenis: "KERING" },
  { no: 92, nama: "Gula", satuan: "Kg", jenis: "KERING" },
  { no: 93, nama: "Garam", satuan: "Kg", jenis: "KERING" },
  { no: 94, nama: "Mentega Kiloan", satuan: "Kg", jenis: "KERING" },
  { no: 95, nama: "Saus Tiram", satuan: "Botol", jenis: "KERING" },
  { no: 96, nama: "Kecap Inggris", satuan: "Botol", jenis: "KERING" },
  { no: 97, nama: "Kaldu Jamur (Totole) 200gr", satuan: "Pcs", jenis: "KERING" },
  { no: 98, nama: "Tepung Terigu", satuan: "Kg", jenis: "KERING" },
  { no: 99, nama: "Tepung Sajiku", satuan: "Dus", jenis: "KERING" },
  { no: 100, nama: "Roti", satuan: "Bungkus", jenis: "KERING" },
  { no: 101, nama: "Tisu Dapur", satuan: "Pcs", jenis: "KERING" },
  { no: 102, nama: "Mr. Muscle", satuan: "Botol", jenis: "KERING" },
  { no: 103, nama: "Kotak Tisu", satuan: "Pcs", jenis: "KERING" },
  { no: 104, nama: "Tisu", satuan: "Pack", jenis: "KERING" },
  { no: 105, nama: "Sabun Lantai", satuan: "Pcs", jenis: "KERING" },
  { no: 106, nama: "Hand Wash", satuan: "Pcs", jenis: "KERING" },
  { no: 107, nama: "Hand Gloves Plastik", satuan: "Kotak", jenis: "KERING" },
  { no: 108, nama: "Plastik Sampah", satuan: "Pack", jenis: "KERING" },
  { no: 109, nama: "Saus Sambal Sachet", satuan: "Pack", jenis: "KERING" },
  { no: 110, nama: "Saus Tomat Sachet", satuan: "Pack", jenis: "KERING" },
  { no: 111, nama: "Jeruk Manis", satuan: "Kg", jenis: "BASAH" },
  { no: 112, nama: "Goodie Bag", satuan: "Pcs", jenis: "KERING" },
  { no: 113, nama: "Minyak Goreng", satuan: "Dus", jenis: "KERING" },
  { no: 114, nama: "Plastik Fiber", satuan: "Pcs", jenis: "KERING" },
  { no: 115, nama: "Gula Merah", satuan: "Kg", jenis: "KERING" },
  { no: 116, nama: "Bawang Bombay", satuan: "Kg", jenis: "BASAH" },
  { no: 117, nama: "Ladaku Merica", satuan: "Renteng", jenis: "KERING" },
  { no: 118, nama: "Biji Pala", satuan: "Kg", jenis: "KERING" },
  { no: 119, nama: "Ketumbar", satuan: "Kg", jenis: "KERING" },
  { no: 120, nama: "Kemiri", satuan: "Kg", jenis: "KERING" },
  { no: 121, nama: "Cengkeh", satuan: "Kg", jenis: "KERING" },
  { no: 122, nama: "Lengkuas", satuan: "Kg", jenis: "BASAH" },
  { no: 123, nama: "Tali Rafia Hitam", satuan: "Ball", jenis: "KERING" },
  { no: 124, nama: "Tali Rafia Warna", satuan: "Ball", jenis: "KERING" },
  { no: 125, nama: "Bubuk Cabe", satuan: "Kg", jenis: "KERING" },
  { no: 126, nama: "Asam Sunti", satuan: "Kg", jenis: "KERING" },
  { no: 127, nama: "Telur Puyuh", satuan: "Papan", jenis: "KERING" },
  { no: 128, nama: "Buah Melon", satuan: "Kg", jenis: "BASAH" },
  { no: 129, nama: "Salak", satuan: "Kg", jenis: "BASAH" },
  { no: 130, nama: "Kecap Asin", satuan: "Botol", jenis: "KERING" },
  { no: 131, nama: "Kunyit Segar", satuan: "Kg", jenis: "BASAH" },
  { no: 132, nama: "Jahe", satuan: "Kg", jenis: "BASAH" },
  { no: 133, nama: "Minyak Wijen", satuan: "Botol", jenis: "KERING" },
  { no: 134, nama: "Saus Teriyaki", satuan: "Botol", jenis: "KERING" },
  { no: 135, nama: "Kain Lap", satuan: "Pack", jenis: "KERING" },
  { no: 136, nama: "Masker Hijab", satuan: "Kotak", jenis: "KERING" },
  { no: 137, nama: "Masker Telinga", satuan: "Kotak", jenis: "KERING" },
  { no: 138, nama: "Karpet Lantai", satuan: "Meter", jenis: "KERING" },
  { no: 139, nama: "Bawang Merah", satuan: "Kg", jenis: "BASAH" },
  { no: 140, nama: "Bawang Putih", satuan: "Kg", jenis: "BASAH" },
  { no: 141, nama: "Kunyit Bubuk", satuan: "Kg", jenis: "KERING" },
  { no: 142, nama: "Biji Wijen", satuan: "Kg", jenis: "KERING" },
  { no: 143, nama: "Susu UHT Plain", satuan: "Dus", jenis: "KERING" },
  { no: 144, nama: "Terasi Udang ABC", satuan: "Pack", jenis: "KERING" },
  { no: 145, nama: "Cetakan Nasi", satuan: "Pcs", jenis: "KERING" },
  { no: 146, nama: "Buah Pisang", satuan: "Pcs", jenis: "BASAH" },
  { no: 147, nama: "Macaroni La Fonte 1kg", satuan: "Kg", jenis: "KERING" },
  { no: 148, nama: "Spagetti La Fonte", satuan: "Pack", jenis: "KERING" },
  { no: 149, nama: "Oregano Kering", satuan: "Botol", jenis: "KERING" },
  { no: 150, nama: "Saus Bolognese 315g", satuan: "Kg", jenis: "KERING" },
  { no: 151, nama: "Saus Tomat Refill 1kg", satuan: "Kg", jenis: "KERING" },
  { no: 152, nama: "Hand Glove Hitam", satuan: "Kotak", jenis: "KERING" },
  { no: 153, nama: "Cuka", satuan: "Botol", jenis: "KERING" },
  { no: 154, nama: "Kapulaga", satuan: "Kg", jenis: "KERING" },
  { no: 155, nama: "Susu Clevo Coklat", satuan: "Dus", jenis: "KERING" },
  { no: 156, nama: "Keju Wincheaze", satuan: "Dus", jenis: "KERING" },
  { no: 157, nama: "Kembang Lawang", satuan: "Kg", jenis: "KERING" },
  { no: 158, nama: "Kecap Bango", satuan: "Bungkus", jenis: "KERING" },
  { no: 159, nama: "Roti Tawar Panjang", satuan: "Bungkus", jenis: "KERING" },
  { no: 160, nama: "Sup Bunjut", satuan: "Pcs", jenis: "KERING" },
  { no: 161, nama: "Keju Slice Prochiz", satuan: "Pack", jenis: "KERING" },
  { no: 162, nama: "Mie Soun 250gr", satuan: "Pack", jenis: "KERING" },
  { no: 163, nama: "Saus Sambal Refill 1kg", satuan: "Kg", jenis: "KERING" },
  { no: 164, nama: "Kencur", satuan: "Kg", jenis: "BASAH" },
  { no: 165, nama: "Sabun Biorf", satuan: "Dus", jenis: "KERING" },
  { no: 166, nama: "Roti Kacang Hijau", satuan: "Pcs", jenis: "KERING" },
  { no: 167, nama: "Kacang Goreng", satuan: "Pcs", jenis: "KERING" },
  { no: 168, nama: "Macaroni Skotel", satuan: "Pcs", jenis: "KERING" },
  { no: 169, nama: "Pisau Cutter", satuan: "Pcs", jenis: "KERING" },
  { no: 170, nama: "Klip Tembak", satuan: "Pcs", jenis: "KERING" },
  { no: 171, nama: "Tepung Tapioka", satuan: "Kg", jenis: "KERING" },
  { no: 172, nama: "Tepung Terigu Dragonfly", satuan: "Kg", jenis: "KERING" },
  { no: 173, nama: "Kaldu Jamur (Totole) 400gr", satuan: "Pcs", jenis: "KERING" },
  { no: 174, nama: "Kacang Tanah", satuan: "Kg", jenis: "KERING" },
  { no: 175, nama: "Keju Top Chiz", satuan: "Dus", jenis: "KERING" },
  { no: 176, nama: "Sutil", satuan: "Pcs", jenis: "KERING" },
  { no: 177, nama: "Kain Lap Ompreng", satuan: "Pcs", jenis: "KERING" },
  { no: 178, nama: "Tepung Maizena", satuan: "Kg", jenis: "KERING" },
  { no: 179, nama: "Baking Powder", satuan: "Kg", jenis: "KERING" },
  { no: 180, nama: "Mamayo (Mayonaise)", satuan: "Dus", jenis: "KERING" },
  { no: 181, nama: "Kacang Merah", satuan: "Kg", jenis: "KERING" },
  { no: 182, nama: "Susu Kental Manis", satuan: "Kaleng", jenis: "KERING" },
  { no: 183, nama: "Asam Jawa", satuan: "Kg", jenis: "KERING" },
  { no: 184, nama: "Mie Telur Cap 3 Ayam", satuan: "Dus", jenis: "KERING" },
  { no: 185, nama: "Teri Medan", satuan: "Kg", jenis: "KERING" },
  { no: 186, nama: "Kecap Ikan", satuan: "Dus", jenis: "KERING" },
  { no: 187, nama: "Madu Kiloan", satuan: "Kg", jenis: "KERING" },
  { no: 188, nama: "Lada Hitam", satuan: "Kg", jenis: "KERING" },
  { no: 189, nama: "Buah Rambutan", satuan: "Kg", jenis: "BASAH" },
  { no: 190, nama: "Keju Wincheese 2 Kg", satuan: "Dus", jenis: "KERING" },
  { no: 191, nama: "Kacang Edamame", satuan: "Kg", jenis: "KERING" },
  { no: 192, nama: "Kacang Tojin", satuan: "Kg", jenis: "KERING" },
  { no: 193, nama: "Nutri Jell", satuan: "Box", jenis: "KERING" },
  { no: 194, nama: "Cup Puding 60ml", satuan: "Pcs", jenis: "KERING" },
  { no: 195, nama: "Cup dan Tutup 100ml", satuan: "Pcs", jenis: "KERING" },
  { no: 196, nama: "Box Kentang", satuan: "Pcs", jenis: "KERING" },
  { no: 197, nama: "Tepung Kanji", satuan: "Kg", jenis: "KERING" },
  { no: 198, nama: "Bubuk Bawang Putih", satuan: "Renteng", jenis: "KERING" },
  { no: 199, nama: "Tepung Beras Rosebrand", satuan: "Dus", jenis: "KERING" },
  { no: 200, nama: "Kacang Ijo", satuan: "Kg", jenis: "KERING" },
  { no: 201, nama: "Parsley Bubuk", satuan: "Botol", jenis: "KERING" },
  { no: 202, nama: "Abon Sapi", satuan: "Kg", jenis: "KERING" },
  { no: 203, nama: "Tusuk Gigi", satuan: "Pack", jenis: "KERING" },
  { no: 204, nama: "Biji Adas", satuan: "Kg", jenis: "KERING" },
  { no: 205, nama: "Cup Piring", satuan: "Pcs", jenis: "KERING" },
  { no: 206, nama: "Bawang Goreng", satuan: "Kg", jenis: "KERING" },
  { no: 207, nama: "Saringan Minyak", satuan: "Pcs", jenis: "KERING" },
  { no: 208, nama: "Tepung Panir", satuan: "Kg", jenis: "KERING" },
  { no: 209, nama: "Susu UHT 1 Liter", satuan: "Dus", jenis: "KERING" },
  { no: 210, nama: "Saus Tiram Adabi 340ml", satuan: "Botol", jenis: "KERING" },
  { no: 211, nama: "Botol Jus 150ml", satuan: "Pcs", jenis: "KERING" },
  { no: 212, nama: "Plastik Klip 10x6", satuan: "Pack", jenis: "KERING" },
  { no: 213, nama: "Plastik Klip 8x5", satuan: "Pack", jenis: "KERING" },
  { no: 214, nama: "Plastik Opp", satuan: "Pack", jenis: "KERING" },
  { no: 215, nama: "Kantong Plastik Besar", satuan: "Pack", jenis: "KERING" },
  { no: 216, nama: "Box Mika Kotak", satuan: "Dus", jenis: "KERING" },
  { no: 217, nama: "Botol Jus 250 ml", satuan: "Pcs", jenis: "KERING" },
  { no: 218, nama: "Cup Bubur 300 ml", satuan: "Dus", jenis: "KERING" },
  { no: 219, nama: "Botol Plastik 125ml", satuan: "Pack", jenis: "KERING" },
  { no: 220, nama: "Plastik 1kg", satuan: "Pack", jenis: "KERING" },
  { no: 221, nama: "Plastik 1/4kg", satuan: "Pack", jenis: "KERING" },
  { no: 222, nama: "Keripik Tempe", satuan: "Pcs", jenis: "KERING" },
  { no: 223, nama: "Kayu Manis", satuan: "Kg", jenis: "KERING" },
  { no: 224, nama: "Royco", satuan: "Kg", jenis: "KERING" },
  { no: 225, nama: "Red Vinegar", satuan: "Botol", jenis: "KERING" },
  { no: 226, nama: "Susu Evaporasi", satuan: "Kaleng", jenis: "KERING" },
  { no: 227, nama: "Cabe Kering", satuan: "Kg", jenis: "KERING" },
  { no: 228, nama: "Pasta Tomat Delmonte", satuan: "Kaleng", jenis: "KERING" },
  { no: 229, nama: "Bay Leaves", satuan: "Botol", jenis: "KERING" },
  { no: 230, nama: "Bubuk Paprika 47gr", satuan: "Botol", jenis: "KERING" },
  { no: 231, nama: "Bubuk Bawang Putih 100gr", satuan: "Pack", jenis: "KERING" },
  { no: 232, nama: "Mentega Simas", satuan: "Dus", jenis: "KERING" },
  { no: 233, nama: "Rice Vinegar 600ml", satuan: "Botol", jenis: "KERING" },
  { no: 234, nama: "Yoghurt Plain 500ml", satuan: "Pcs", jenis: "KERING" },
  { no: 235, nama: "Saus ABC Tomat", satuan: "Jerigen", jenis: "KERING" },
  { no: 236, nama: "Knorr Chicken Powder", satuan: "Bungkus", jenis: "KERING" },
  { no: 237, nama: "Susu Full Cream", satuan: "Pcs", jenis: "KERING" },
  { no: 238, nama: "Bay Leaves", satuan: "Botol", jenis: "KERING" },
  { no: 239, nama: "Demi Glace 1kg", satuan: "Pcs", jenis: "KERING" },
  { no: 240, nama: "Lea Perrins Sauce 284ml", satuan: "Botol", jenis: "KERING" },
  { no: 241, nama: "Apel Hijau", satuan: "Kg", jenis: "BASAH" },
  { no: 242, nama: "White Vinegar 150ml", satuan: "Botol", jenis: "KERING" },
  { no: 243, nama: "Saus Tomat Delmonte", satuan: "Jerigen", jenis: "KERING" },
  { no: 244, nama: "Saus Sambal Delmonte", satuan: "Jerigen", jenis: "KERING" },
  { no: 245, nama: "Dark Soy Sauce", satuan: "Botol", jenis: "KERING" },
  { no: 246, nama: "Maggie Seasoning Kecap", satuan: "Botol", jenis: "KERING" },
  { no: 247, nama: "Madu Rasa Murni", satuan: "Botol", jenis: "KERING" },
  { no: 248, nama: "Kecap Bango", satuan: "Jerigen", jenis: "KERING" },
];

async function main() {
  console.log("Seeding items...");
  await prisma.opnameEntry.deleteMany();
  await prisma.item.deleteMany();
  for (const item of items) {
    await prisma.item.create({ data: { ...item, stokAwal: 0, aktif: true } });
  }
  console.log(`✓ ${items.length} items`);

  console.log("\nSeeding users...");
  const existingUsers = await prisma.user.count();
  if (existingUsers === 0) {
    await prisma.user.createMany({
      data: [
        { id: "00000000-0000-0000-0000-000000000001", email: "admin@sppg.com", nama: "Admin SPBG", password: "admin123", role: "ADMIN" },
        { id: "00000000-0000-0000-0000-000000000002", email: "korlap@sppg.com", nama: "Korlap Gudang", password: "dapur123", role: "KORLAP" },
        { id: "00000000-0000-0000-0000-000000000003", email: "korlap2@sppg.com", nama: "Korlap 2", password: "dapur123", role: "KORLAP" },
        { id: "00000000-0000-0000-0000-000000000004", email: "kagudang@sppg.com", nama: "Kepala Gudang", password: "dapur123", role: "KEPALA_GUDANG" },
        { id: "00000000-0000-0000-0000-000000000005", email: "akuntan@sppg.com", nama: "Akuntan", password: "dapur123", role: "AKUNTAN" },
      ],
    });
    console.log("✓ 5 users created via Prisma (seed IDs)");
  } else {
    console.log(`∼ ${existingUsers} users already exist, skipping`);
  }

  // Seed role permissions
  const existingPerms = await prisma.rolePermission.count();
  if (existingPerms === 0) {
    await prisma.rolePermission.createMany({
      data: [
        { role: "ADMIN", permissions: JSON.stringify(["input_opname", "view_laporan", "manage_komoditas", "manage_users", "manage_roles", "manage_settings"]) },
        { role: "KEPALA_GUDANG", permissions: JSON.stringify(["input_opname", "view_laporan", "manage_komoditas"]) },
        { role: "KORLAP", permissions: JSON.stringify(["input_opname", "view_laporan", "manage_komoditas"]) },
        { role: "AKUNTAN", permissions: JSON.stringify(["view_laporan"]) },
      ],
    });
    console.log("✓ Role permissions seeded");
  }

  console.log("\nSeed complete.");
}

main()
  .catch((e) => {
    console.error("Seed failed:", e.message);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
